[package]
name = "neural-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neural = { path = "../neural" }
bincode = { version = "2.0.0-rc.1", features = [ "derive" ] }
byteorder = "1.4.3"